apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-source
spec:
  type: git
  params:
  - name: revision
    value: master
  - name: url
    value: https://github.ibm.com/AROBERTS/myjavatest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: docker-image
spec:
  type: image
  params:
  - name: url
    value: docker.io/adamroberts/my-java-test-project
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: microclimate-pipeline-run # Remember subsequent ones should be uniquely named, I don't auto-delete
spec:
  pipelineRef:
    name: microclimate-pipeline # Change if you want to use a different pipeline
  params:
    - name: chart-dir
      value: "chart"
    - name: repository-name
      value: "myjavatest"
    - name: release-name
      value: "simple-node-release"
    - name: target-namespace
      value: "default"
    - name: image-name
      value: "adamroberts/my-simple-node-app"
    - name: image-tag
      value: "latest"
    - name: replace-repo
      value: "https://registry.ng.bluemix.net/v2/replace-me-namespace/node"
    - name: replace-tag
      value: "v1.0.0"

  trigger:
    type: manual
  serviceAccount: 'default'
  resources:
  - name: git-source
    resourceRef:
      name: git-source
  - name: docker-image
    resourceRef:
      name: docker-image
