apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: simple-pipeline-push-binding
spec:
  params:
  - ref: gitrevision
    value: $(body.head_commit.id)
  - ref: gitrepositoryurl
    value: $(body.repository.clone_url)
  - ref: docker-tag
    value: $(body.repository.name):$(body.head_commit.id)
  - ref: event-type
    value: $(header.X-Github-Event)
  - ref: webhooks-tekton-git-branch
    value: $(body.webhooks-tekton-git-branch)
